"""create tables

Revision ID: 312bf60cc611
Revises: 
Create Date: 2024-02-10 23:08:51.108730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312bf60cc611'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('openai_token', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id'),
    schema='gpt'
    )
    op.create_table('chat',
    sa.Column('chat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=True),
    sa.Column('context_json', sa.JSON(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=False),
    sa.Column('token_usage', sa.Float(precision=5).with_variant(sa.FLOAT(), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['gpt.user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'chat_id'),
    schema='gpt'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat', schema='gpt')
    op.drop_table('user', schema='gpt')
    # ### end Alembic commands ###
